/**
 * Ícones Lucide usados no portal.
 *
 * O registro é explícito de propósito: importar o pacote inteiro traz os ~2.100
 * ícones da biblioteca para o bundle. Ao adicionar um `data-lucide="..."` novo
 * (em uma tela ou em um componente do design system), inclua o nome aqui — em
 * desenvolvimento, um ícone ausente aparece como aviso no console.
 */

import {
  Activity,
  ArrowLeft,
  ArrowRight,
  Bell,
  BellOff,
  BellRing,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarClock,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleCheck,
  CircleCheckBig,
  CircleX,
  ClipboardList,
  Clock,
  Copy,
  Database,
  Download,
  Eye,
  FileText,
  FileUp,
  FolderOpen,
  House,
  Inbox,
  Info,
  Landmark,
  Lock,
  Receipt,
  RotateCw,
  Search,
  Send,
  Settings,
  UploadCloud,
  UserPlus,
  Wallet,
  X,
  Zap
} from 'lucide';

/** Nome em kebab-case (como aparece em `data-lucide`) → definição do ícone. */
export const ICONES = {
  activity: Activity,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  bell: Bell,
  'bell-off': BellOff,
  'bell-ring': BellRing,
  'building-2': Building2,
  calendar: Calendar,
  'calendar-check': CalendarCheck,
  'calendar-clock': CalendarClock,
  check: Check,
  'check-check': CheckCheck,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'circle-check': CircleCheck,
  'circle-check-big': CircleCheckBig,
  'circle-x': CircleX,
  'clipboard-list': ClipboardList,
  clock: Clock,
  copy: Copy,
  database: Database,
  download: Download,
  eye: Eye,
  'file-text': FileText,
  'file-up': FileUp,
  'folder-open': FolderOpen,
  house: House,
  inbox: Inbox,
  info: Info,
  landmark: Landmark,
  lock: Lock,
  receipt: Receipt,
  'rotate-cw': RotateCw,
  search: Search,
  send: Send,
  settings: Settings,
  'upload-cloud': UploadCloud,
  'user-plus': UserPlus,
  wallet: Wallet,
  x: X,
  zap: Zap
};
